//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        ExaminationClient.ServiceReference1.UserLoginResponse UserLogin(ExaminationClient.ServiceReference1.UserLoginRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.UserLoginResponse> UserLoginAsync(ExaminationClient.ServiceReference1.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        ExaminationClient.ServiceReference1.RegisterUserResponse RegisterUser(ExaminationClient.ServiceReference1.RegisterUserRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.RegisterUserResponse> RegisterUserAsync(ExaminationClient.ServiceReference1.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectTypes", ReplyAction="http://tempuri.org/IService1/GetSubjectTypesResponse")]
        string[] GetSubjectTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectTypes", ReplyAction="http://tempuri.org/IService1/GetSubjectTypesResponse")]
        System.Threading.Tasks.Task<string[]> GetSubjectTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectLevels", ReplyAction="http://tempuri.org/IService1/GetSubjectLevelsResponse")]
        string[] GetSubjectLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectLevels", ReplyAction="http://tempuri.org/IService1/GetSubjectLevelsResponse")]
        System.Threading.Tasks.Task<string[]> GetSubjectLevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjects", ReplyAction="http://tempuri.org/IService1/GetSubjectsResponse")]
        ExaminationClient.ServiceReference1.GetSubjectsResponse GetSubjects(ExaminationClient.ServiceReference1.GetSubjectsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjects", ReplyAction="http://tempuri.org/IService1/GetSubjectsResponse")]
        System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.GetSubjectsResponse> GetSubjectsAsync(ExaminationClient.ServiceReference1.GetSubjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveScore", ReplyAction="http://tempuri.org/IService1/SaveScoreResponse")]
        ExaminationClient.ServiceReference1.SaveScoreResponse SaveScore(ExaminationClient.ServiceReference1.SaveScoreRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveScore", ReplyAction="http://tempuri.org/IService1/SaveScoreResponse")]
        System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.SaveScoreResponse> SaveScoreAsync(ExaminationClient.ServiceReference1.SaveScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudyData", ReplyAction="http://tempuri.org/IService1/GetStudyDataResponse")]
        ExaminationClient.ServiceReference1.GetStudyDataResponse GetStudyData(ExaminationClient.ServiceReference1.GetStudyDataRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudyData", ReplyAction="http://tempuri.org/IService1/GetStudyDataResponse")]
        System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.GetStudyDataResponse> GetStudyDataAsync(ExaminationClient.ServiceReference1.GetStudyDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudyRankingList", ReplyAction="http://tempuri.org/IService1/GetStudyRankingListResponse")]
        System.Data.DataTable GetStudyRankingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudyRankingList", ReplyAction="http://tempuri.org/IService1/GetStudyRankingListResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetStudyRankingListAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UserLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Guid userId;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(bool UserLoginResult, string errText, System.Guid userId) {
            this.UserLoginResult = UserLoginResult;
            this.errText = errText;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RegisterUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errText;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(bool RegisterUserResult, string errText) {
            this.RegisterUserResult = RegisterUserResult;
            this.errText = errText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjects", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string level;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string type;
        
        public GetSubjectsRequest() {
        }
        
        public GetSubjectsRequest(int num, string level, string type) {
            this.num = num;
            this.level = level;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ExaminationEntity.SubjectInfo[] GetSubjectsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errText;
        
        public GetSubjectsResponse() {
        }
        
        public GetSubjectsResponse(ExaminationEntity.SubjectInfo[] GetSubjectsResult, string errText) {
            this.GetSubjectsResult = GetSubjectsResult;
            this.errText = errText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveScore", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int score;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int subNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string subLevel;
        
        public SaveScoreRequest() {
        }
        
        public SaveScoreRequest(System.Guid id, string name, int score, int subNum, string subLevel) {
            this.id = id;
            this.name = name;
            this.score = score;
            this.subNum = subNum;
            this.subLevel = subLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveScoreResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveScoreResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errText;
        
        public SaveScoreResponse() {
        }
        
        public SaveScoreResponse(bool SaveScoreResult, string errText) {
            this.SaveScoreResult = SaveScoreResult;
            this.errText = errText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudyData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudyDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime end;
        
        public GetStudyDataRequest() {
        }
        
        public GetStudyDataRequest(System.Guid id, string name, System.DateTime start, System.DateTime end) {
            this.id = id;
            this.name = name;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudyDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudyDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetStudyDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errText;
        
        public GetStudyDataResponse() {
        }
        
        public GetStudyDataResponse(System.Data.DataTable GetStudyDataResult, string errText) {
            this.GetStudyDataResult = GetStudyDataResult;
            this.errText = errText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExaminationClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExaminationClient.ServiceReference1.IService1>, ExaminationClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExaminationClient.ServiceReference1.UserLoginResponse ExaminationClient.ServiceReference1.IService1.UserLogin(ExaminationClient.ServiceReference1.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public bool UserLogin(string name, string password, out string errText, out System.Guid userId) {
            ExaminationClient.ServiceReference1.UserLoginRequest inValue = new ExaminationClient.ServiceReference1.UserLoginRequest();
            inValue.name = name;
            inValue.password = password;
            ExaminationClient.ServiceReference1.UserLoginResponse retVal = ((ExaminationClient.ServiceReference1.IService1)(this)).UserLogin(inValue);
            errText = retVal.errText;
            userId = retVal.userId;
            return retVal.UserLoginResult;
        }
        
        public System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.UserLoginResponse> UserLoginAsync(ExaminationClient.ServiceReference1.UserLoginRequest request) {
            return base.Channel.UserLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExaminationClient.ServiceReference1.RegisterUserResponse ExaminationClient.ServiceReference1.IService1.RegisterUser(ExaminationClient.ServiceReference1.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public bool RegisterUser(string name, string password, out string errText) {
            ExaminationClient.ServiceReference1.RegisterUserRequest inValue = new ExaminationClient.ServiceReference1.RegisterUserRequest();
            inValue.name = name;
            inValue.password = password;
            ExaminationClient.ServiceReference1.RegisterUserResponse retVal = ((ExaminationClient.ServiceReference1.IService1)(this)).RegisterUser(inValue);
            errText = retVal.errText;
            return retVal.RegisterUserResult;
        }
        
        public System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.RegisterUserResponse> RegisterUserAsync(ExaminationClient.ServiceReference1.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public string[] GetSubjectTypes() {
            return base.Channel.GetSubjectTypes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSubjectTypesAsync() {
            return base.Channel.GetSubjectTypesAsync();
        }
        
        public string[] GetSubjectLevels() {
            return base.Channel.GetSubjectLevels();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSubjectLevelsAsync() {
            return base.Channel.GetSubjectLevelsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExaminationClient.ServiceReference1.GetSubjectsResponse ExaminationClient.ServiceReference1.IService1.GetSubjects(ExaminationClient.ServiceReference1.GetSubjectsRequest request) {
            return base.Channel.GetSubjects(request);
        }
        
        public ExaminationEntity.SubjectInfo[] GetSubjects(int num, string level, string type, out string errText) {
            ExaminationClient.ServiceReference1.GetSubjectsRequest inValue = new ExaminationClient.ServiceReference1.GetSubjectsRequest();
            inValue.num = num;
            inValue.level = level;
            inValue.type = type;
            ExaminationClient.ServiceReference1.GetSubjectsResponse retVal = ((ExaminationClient.ServiceReference1.IService1)(this)).GetSubjects(inValue);
            errText = retVal.errText;
            return retVal.GetSubjectsResult;
        }
        
        public System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.GetSubjectsResponse> GetSubjectsAsync(ExaminationClient.ServiceReference1.GetSubjectsRequest request) {
            return base.Channel.GetSubjectsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExaminationClient.ServiceReference1.SaveScoreResponse ExaminationClient.ServiceReference1.IService1.SaveScore(ExaminationClient.ServiceReference1.SaveScoreRequest request) {
            return base.Channel.SaveScore(request);
        }
        
        public bool SaveScore(System.Guid id, string name, int score, int subNum, string subLevel, out string errText) {
            ExaminationClient.ServiceReference1.SaveScoreRequest inValue = new ExaminationClient.ServiceReference1.SaveScoreRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.score = score;
            inValue.subNum = subNum;
            inValue.subLevel = subLevel;
            ExaminationClient.ServiceReference1.SaveScoreResponse retVal = ((ExaminationClient.ServiceReference1.IService1)(this)).SaveScore(inValue);
            errText = retVal.errText;
            return retVal.SaveScoreResult;
        }
        
        public System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.SaveScoreResponse> SaveScoreAsync(ExaminationClient.ServiceReference1.SaveScoreRequest request) {
            return base.Channel.SaveScoreAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExaminationClient.ServiceReference1.GetStudyDataResponse ExaminationClient.ServiceReference1.IService1.GetStudyData(ExaminationClient.ServiceReference1.GetStudyDataRequest request) {
            return base.Channel.GetStudyData(request);
        }
        
        public System.Data.DataTable GetStudyData(System.Guid id, string name, System.DateTime start, System.DateTime end, out string errText) {
            ExaminationClient.ServiceReference1.GetStudyDataRequest inValue = new ExaminationClient.ServiceReference1.GetStudyDataRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.start = start;
            inValue.end = end;
            ExaminationClient.ServiceReference1.GetStudyDataResponse retVal = ((ExaminationClient.ServiceReference1.IService1)(this)).GetStudyData(inValue);
            errText = retVal.errText;
            return retVal.GetStudyDataResult;
        }
        
        public System.Threading.Tasks.Task<ExaminationClient.ServiceReference1.GetStudyDataResponse> GetStudyDataAsync(ExaminationClient.ServiceReference1.GetStudyDataRequest request) {
            return base.Channel.GetStudyDataAsync(request);
        }
        
        public System.Data.DataTable GetStudyRankingList() {
            return base.Channel.GetStudyRankingList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetStudyRankingListAsync() {
            return base.Channel.GetStudyRankingListAsync();
        }
    }
}
